field: a2dcd655-a57b-404b-af71-b272c5ed6621
fieldLayouts:
  f4a67f6a-f3da-4faf-ae5e-6a2188cbec27:
    tabs:
      -
        fields:
          2c3d2381-ef86-4a6e-a661-b9e734c28d28:
            required: true
            sortOrder: 2
          d59dcf4a-4a35-43ff-9f2e-5c6334a4ed34:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  2c3d2381-ef86-4a6e-a661-b9e734c28d28:
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: ''
    name: Style
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  d59dcf4a-4a35-43ff-9f2e-5c6334a4ed34:
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: ''
    name: Link
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames: '*'
      autoNoReferrer: '1'
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: '1'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - '1'
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - '1'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - '1'
    translationKeyFormat: null
    translationMethod: site
    type: typedlinkfield\fields\LinkField
handle: button
name: Button
sortOrder: 4
