fieldLayouts:
  0eca2e49-c2c6-481a-b152-2c96d3a7c1aa:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a2dcd655-a57b-404b-af71-b272c5ed6621
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c1b4c446-c55a-4be3-a3e6-b07307043eae
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: home
hasTitleField: false
name: Home
section: 7d93f9fa-b037-4efb-a916-d7367dfec86d
sortOrder: 1
titleFormat: '{section.name|raw}'
