fieldLayouts:
  b685492b-68d9-43c9-9a86-586b2b0073bf:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a2dcd655-a57b-404b-af71-b272c5ed6621
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c1b4c446-c55a-4be3-a3e6-b07307043eae
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: imprint
hasTitleField: false
name: Imprint
section: f8536acb-782f-462a-8943-624fd61dd89b
sortOrder: 1
titleFormat: '{section.name|raw}'
