fieldLayouts:
  1cde5b0c-7948-4fcd-aee7-44c7467b3608:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a2dcd655-a57b-404b-af71-b272c5ed6621
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c1b4c446-c55a-4be3-a3e6-b07307043eae
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: page
hasTitleField: true
name: Page
section: 2ef4c03a-16ca-4899-bd3f-8882715a3c7d
sortOrder: 1
titleFormat: ''
