email:
  fromEmail: urs@21sieben.de
  fromName: 'Craft Webpack Scaffold'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  6d3a100d-2416-43b3-913c-6206c7a61231:
    name: Common
siteGroups:
  a160c4ba-1b94-4a79-ae3c-8bedb0b16477:
    name: 'Craft Webpack Scaffold'
sites:
  665b92a3-8815-4c5e-9908-277d2d6ea628:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'Craft Webpack Scaffold'
    primary: true
    siteGroup: a160c4ba-1b94-4a79-ae3c-8bedb0b16477
    sortOrder: 1
system:
  edition: solo
  live: true
  name: 'Craft Webpack Scaffold'
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
