contentColumnType: text
fieldGroup: 19d90b1a-02b3-43b7-af00-2fd238777f9b
handle: menuLink
instructions: ''
name: 'Menu Link'
searchable: true
settings:
  allowCustomText: '1'
  allowTarget: '1'
  allowedLinkNames: '*'
  autoNoReferrer: '1'
  defaultLinkName: entry
  defaultText: ''
  enableAriaLabel: ''
  enableTitle: '1'
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - '1'
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - '1'
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - '1'
translationKeyFormat: null
translationMethod: site
type: typedlinkfield\fields\LinkField
