field: d8fd50e1-7d58-4da7-a3e5-67e3ab3467dc
fieldLayouts:
  47b48283-8854-46e1-ae9c-3b9282109e1e:
    tabs:
      -
        fields:
          25c732bd-b25e-4311-9ccf-30130ee35a0e:
            required: true
            sortOrder: 2
          63594945-f4dd-4173-a595-5d65cd2f815f:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  25c732bd-b25e-4311-9ccf-30130ee35a0e:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  63594945-f4dd-4173-a595-5d65cd2f815f:
    contentColumnType: string
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
