enableVersioning: true
handle: serviceMenu
name: 'Service menu'
propagationMethod: all
siteSettings:
  610abf1d-0955-4e63-91d9-1cb77062c2ea:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
  665b92a3-8815-4c5e-9908-277d2d6ea628:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
structure:
  maxLevels: 1
  uid: 528438d6-bdee-49b6-8246-f12b537eb92e
type: structure
